import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  LucideAngularModule,
  Github,
  Linkedin,
  Mail,
  Phone,
  MapPin,
  ExternalLink,
  Download,
  Menu,
  X,
  ChevronUp,
  ArrowRight,
  Code2,
  Server,
  Globe,
  Zap,
  Shield,
  TestTube,
  Database,
  Cpu,
  Star,
  Award,
  GraduationCap,
  Building,
  Calendar,
  CheckCircle,
  Circle,
  ChevronLeft,
  ChevronRight,
  Copy,
  Check
} from 'lucide-angular';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        Github,
        Linkedin,
        Mail,
        Phone,
        MapPin,
        ExternalLink,
        Download,
        Menu,
        X,
        ChevronUp,
        ArrowRight,
        Code2,
        Server,
        Globe,
        Zap,
        Shield,
        TestTube,
        Database,
        Cpu,
        Star,
        Award,
        GraduationCap,
        Building,
        Calendar,
        CheckCircle,
        Circle,
        ChevronLeft,
        ChevronRight,
        Copy,
        Check
      }),
    ),
  ],
};
